version: '3.8'

services:
  back-end:
    depends_on:
      - postgres
    build: ./
    ports:
      - 3333:3333
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/study_refreshToken?schema=public
    command: ./entrypoint.sh
    
  postgres:
    image: postgres:15.1-bullseye
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
    # aqui criamos onde os dados do banco de dados serão armazenados
      - postgres:/data/db

volumes:
  postgres:
